print("This is number calculator!!!")
print("-----------------------------------------------------")
num1=float(input("First number you want to calculate: "))
num2=float(input("Second number you want to calculate: "))
print("-----------------------------------------------------")
print("Here's your answer!!")
print(num1,"+",num2,"=",num1+num2)
print(num1,"-",num2,"=",num1-num2)
print(num1,"x",num2,"=",num1*num2)
print(num1,"÷",num2,"=",num1/num2)
print("-----------------------------------------------------")